services:
  - type: web
    name: smartnotes-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      mkdir -p logs
      pip install -r requirements/prod.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd backend && gunicorn smartnotes.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: smartnotes.settings.prod
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: smartnotes-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: smartnotes-db
    plan: free
    region: oregon